# dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hw4-prod
resources:
  - ../../base
  - ingress.yaml
patches:
- path: patch-frontapp.yaml
- path: patch-backapp.yaml
