apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backapp.name }}
  labels:
    training: {{ .Values.backapp.service.selector.training }}
    homework: {{ .Values.backapp.name }}
spec:
  replicas: {{ .Values.backapp.replicaCount }}
  selector:
    matchLabels:
      training: {{ .Values.backapp.service.selector.training }}
      homework: {{ .Values.backapp.name }}
  template:
    metadata:
      labels:
        training: {{ .Values.backapp.service.selector.training }}
        homework: {{ .Values.backapp.name }}
    spec:
      containers:
        - name: {{ .Values.backapp.name }}
          image: "{{ .Values.backapp.image.repository }}:{{ .Values.backapp.image.tag }}"
          env:
            - name: {{ .Values.backapp.backapp_name }}
              value: {{ .Values.backapp.name }}
            - name: {{ .Values.backapp.backapp_java }}
              value: {{ .Values.backapp.backapp_java_value }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
