apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backapp.name }}
  labels:
    training: {{ .Values.backapp.service.selector.training }}
    homework: {{ .Values.backapp.name }}
spec:
  type: {{ .Values.backapp.service.type }}
  ports:
    - port: {{ .Values.backapp.service.port }}
      targetPort: {{ .Values.backapp.service.targetport }}
      protocol: TCP
      name: http
  selector:
    homework: {{ .Values.backapp.name }}
    training: {{ .Values.backapp.service.selector.training }}
