apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backapp.name }}
  labels:
    training: {{ .Values.backapp.service.selector.training }}
    homework: {{ .Values.backapp.name }}
spec:
  replicas: {{ .Values.backapp.replicaCount }}
  selector:
    matchLabels:
      training: {{ .Values.backapp.service.selector.training }}
      homework: {{ .Values.backapp.name }}
  template:
    metadata:
      labels:
        training: {{ .Values.backapp.service.selector.training }}
        homework: {{ .Values.backapp.name }}
    spec:
      containers:
        - name: {{ .Values.backapp.name }}
          image: "{{ .Values.backapp.image.repository }}:{{ .Values.backapp.image.tag }}"
          env:
            - name: APP_DEFAULT_MESSAGE
              value: {{ .Values.backapp.default_message }}
            - name: JAVA_OPTS
              value: {{ .Values.backapp.java_opts }}
            {{- with .Values.extraEnv }}
            {{- range . }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
