apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontapp.name }}
  labels:
    training: block4
    homework: frontapp
spec:
  type: {{ .Values.frontapp.service.type }}
  ports:
    - port: {{ .Values.frontapp.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.backapp.name }}
    homework: frontapp
    training: block4
