apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontapp.name }}
  labels:
    training: {{ .Values.frontapp.service.selector.training }}
    homework: {{ .Values.frontapp.name }}
spec:
  type: {{ .Values.frontapp.service.type }}
  ports:
    - port: {{ .Values.frontapp.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    homework: {{ .Values.frontapp.name }}
    training: {{ .Values.frontapp.service.selector.training }}
