apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontapp.name }}
  labels:
    training: {{ .Values.frontapp.service.selector.training }}
    homework: {{ .Values.frontapp.name }}
spec:
  replicas: {{ .Values.frontapp.replicaCount }}
  selector:
    matchLabels:
      training: {{ .Values.frontapp.service.selector.training }}
      homework: {{ .Values.frontapp.name }}
  template:
    metadata:
      labels:
        training: {{ .Values.frontapp.service.selector.training }}
        homework: {{ .Values.frontapp.name }}
    spec:
      containers:
        - name: {{ .Values.frontapp.name }}
          image: "{{ .Values.frontapp.image.repository }}:{{ .Values.frontapp.image.tag }}"
          env:
            - name: APP_DEFAULT_MESSAGE
              value: {{ .Values.frontapp.default_message }}
            - name: JAVA_OPTS
              value: {{ .Values.frontapp.java_opts }}
            - name: BACK_URL
              value: {{ .Values.frontapp.back_url }}
            {{- with .Values.extraEnv }}
            {{- range . }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
