apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontapp.name }}
  labels:
    training: {{ .Values.frontapp.service.selector.training }}
    homework: {{ .Values.frontapp.name }}
spec:
  replicas: {{ .Values.frontapp.replicaCount }}
  selector:
    matchLabels:
      training: {{ .Values.frontapp.service.selector.training }}
      homework: {{ .Values.frontapp.name }}
  template:
    metadata:
      labels:
        training: {{ .Values.frontapp.service.selector.training }}
        homework: {{ .Values.frontapp.name }}
    spec:
      containers:
        - name: {{ .Values.frontapp.name }}
          image: "{{ .Values.frontapp.image.repository }}:{{ .Values.frontapp.image.tag }}"
          env:
            - name: {{ .Values.frontapp.back_url }}
              value: {{ .Values.frontapp.backurl_value }}
            - name: {{ .Values.frontapp.back_url_name }}
              value: {{ .Values.frontapp.name }}
            - name: {{ .Values.frontapp.back_url_java }}
              value: ""
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
