# backapp.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backapp
  labels:
    training: block4
    homework: backapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backapp
  template:
    metadata:
      labels:
        app: backapp
    spec:
      containers:
        - name: backapp
          image: quay.io/drsylent/cubix/block3/homework-backapp:springboot3
          env:
            - name: APP_DEFAULT_MESSAGE
              value: "backapp"
            - name: JAVA_OPTS
              value: -Dspring.main.banner-mode=off
          ports:
            - containerPort: 8080          


---
apiVersion: v1
kind: Service
metadata:
  name: backapp
  labels:
    homework: backapp
    training: block4
spec:
  type: ClusterIP
  selector:
    homework: backapp
    training: block4
  ports:
    - port: 8080
      targetPort: 8080
