# frontapp.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontapp
  labels:
    training: block4
    homework: frontapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontapp
  template:
    metadata:
      labels:
        app: frontapp
    spec:
      containers:
        - name: frontapp
          image: quay.io/drsylent/cubix/block3/homework-frontapp:springboot3
          env:
            - name: BACK_URL
              value: "http://backapp"
            - name: APP_DEFAULT_MESSAGE
              value: "frontapp"
            - name: JAVA_OPTS
              value: ""
          ports:
            - containerPort: 8080
---                  
apiVersion: v1
kind: Service
metadata:
  name: frontapp
  labels:
    homework: frontapp
    training: block4
spec:
  type: NodePort
  selector:
    homework: frontapp
    training: block4
  ports:
    - port: 8080
      targetPort: 8080